import csv
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string

# nltk.download('punkt')
nltk.data.path.append('nltk_data')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

csv_data = """Qualifications,category,Fields,Job Titles,Interests,Skills,Goals
12th,law ,Lawyer(advocate) with LLB Degree,,"Justice, Legal Rights, Courtroom Advocacy, Legal Research","Argumentation, Communication, Critical Thinking, Research, Persuasion",I want to become a successful Lawyer.
12th,Law ,Judge with LLB Degree,,"Law Interpretation, Justice Delivery, Legal Ethics, Decision-making","Legal Knowledge, Impartiality, Analytical Reasoning, Patience, Integrity","I want to become a Judge, lawyer."
12th,Law ,Corporate Lawyer  with LLB Degree,,"Business Law, Mergers & Acquisitions, Company Regulations","Commercial Awareness, Negotiation, Contract Drafting, Problem-solving, Communication","I want to become a successful lawyer, Coporpate Lawyer "
12th,Law ,Criminal Lawyer with LLB Degree,,"Crime Cases, Criminal Justice, Defense and Prosecution","Investigation, Argumentation, Analytical Skills, Communication, Resilience",I want to become a Criminal Lawyer.
12th,Law ,Family Lawyer with LLB Degree,,"Marriage Law, Divorce Cases, Child Custody, Family Disputes","Mediation, Counseling, Negotiation, Patience, Emotional Intelligence",I want to become a successful family lawyer.
12th,Engineering ,Computer Science and Engineering with BE/B-TECH,,"Web Development, Software Development, Frontend Development, Full stack development, Artificial Intelligence, Machine Learning, Data science, Cyber Security, Data Analytics, cloud Computing.","C, C++, Java, Python, JavaScript, Data structures and algorithms, Database management system, operating systems, Cloud computing, Blockchain Development.","I want to become a successful software developer, software engineer, web developer, Frontend developer, backend developer, full stack developer. "
12th,Engineering ,Mechanical Engineering with BE/B-TECH,,"Interest in machines, Cars, Engines, Product Design, Automobiles, 3D printing and prototyping, Industrial automation and robotics, Product innovation and design."," Mathematics and Physics, AutoCAD, Engineering fundamentals, Thermodynamics, Fluid Mechanics, Material Science, Manufacturing Processes, Robotics, Problem Solving, HIVAC Systems, Finite Element Analysis, ",I want to become a successful mechanical engineer.
12th,Engineering ,Civil Engineering with BE/B-TECH,,"Passion for building structures, Urban development, environmental sustainability, Designing eco-friendly cities, skyscraper and mega-structure projects, Green building technology, Bridge architecture and design.","Structural Analysis, AutoCAD, Construction Management, Surveying, Estimation and costing, Geotechnical Engineering, Building Information Modelling, Urban Planning, Soil Mechanics, Transportation Engineering, Environmental Engineering. ",I want to become a successful civil engineer
12th,Engineering ,Electrical Engineering with BE/B-TECH,,"Power Systems, Electrical Machines, Electric innovation, Power generation, Energy conservation, Smart grids, Electronics, Electric vehicles and motors, Power transmission.","Power systems, Electrical Machines, Control systems, Circuit Theory, MATLAB/Simulink, Renewable, Energy, Electronics, Smart Grids Technology, SCADA Systems, High voltage Engineering, Energy Storage Systems.",I want to become a successful Electrical engineer
12th,Engineering ,Electronics and Telecommunication Engineering with BE/B-TECH,,"Fascination with gadgets, Electronics, Wireless systems, Building Circuits, Internet of Things, Mobile Communication, Embedded Systems, Smart devices and home automation, radio technology, Satellite communication, Tech gadgets teardown, Electronics DIY projects.","Circuit Design, Embedded Systems, VLSI Design, Communication Systems, Signal, Processing, Programming(Verilog, C), PCB Designing, Internet of Things, FPGA Programming, Wireless Communication Protocols, Artificial Neural Networks.",I want to become a successful Electronics and Telecommunication Engineer
12th,Engineering,Mining Engineering with BE/B-TECH,,"Interest in Natural resources, Mining technology, Earth science, Environmental impact of mining, Exploring remote areas for resources, Sustainable mining practices, Metallurgy and mineral processing, Geological field work.","Rock Mechanics, Mine Surveying, Mineral Processing, Safety Management, Environmental Engineering, Geology, Mine planning and Design, Drilling and Blasting Techniques, Mineral Economics, Underground and Surface mining techniques, Mine Health and Safety.",I want to become a successful mining engineer
12th,Medical,MBBS ,,"Healthcare, Problem-solving, Surgery, Diagnosis, Medicine","Anatomy, Communication, Critical thinking, Decision-making, Stress Management",I want to become a successful doctor.
12th,Medical,Dentist with  BDS,,"Oral, Hygiene, Procedures, Dentistry, Technology","Manual dexterity, Communication, Diagnosis, Anatomy, Patient care",I want to become a successful doctor.
12th,Medical,BHMS,,"Alternative medicine, Holistic health, Natural remedies, Patient care","Diagnosis, Homeopathy, Research, Empathy, Analytical skills",I want to become a successful doctor
12th,Medical,Pharmacy with B-phram/D-Phram,,"Pharmaceuticals, Drug formulation, Medication, Patient health","Pharmacology, chemistry, Accuracy, Organization, Counseling",I want to become a successful doctor
12th,Medical,Gynaecologist with MBBS,,"Reproductive health, Pregnancy, Childbirth, Women's health","Obstetrics, Surgery, Communication, Diagnosis, Patient care",I want to become a successful doctor
12th,Defence,Army,,"Leadership, Strategy, Survival, Weapons, Strategy Games Command, Training, StrengthBuilding, CombatFitness, StrategyDevelopment, NationalUnity, Patriotism"," Discipline,Leadership, Teamwork, Strategy, Endurance Strength, Focus ,Courage, Self Defense, Weapons Handling, SurvivalTraining,FirstAid, military planning ",I want to join defence field
12th,Defence,Navy,,"Navigation, SubmarineWarfare, SeaManship, Radar, Sonar, Swimming, CombatFitness, Oceanography, NavalTechnology, InternationalWater","Under water Survival, Weapon Systems, Radar Systems, Sonar Technology, Ship Maintenance, Crisis Management, Resource Management, Combat Swimming, Planning, Multi-Tasking, Navigation, Damage Control, Emergency Response, Search And Rescue",I want to join defence field
12th,Defence,Air force,,"AirWarfare, FighterJet, Bombing, AirDefense, Dogfighting, AirPatrolling, Propulsion, Avionics, AirCraftDesign, FlightControl, Navigation, Command, TacticalLeadership","Focus, Piloting, FlightControl, AirRefueling, CombatFlying, AircraftMaintenance, AirDefense, SearchAndRescue, SurvivalSkills, WeaponsHandling, Fitness, Stamina, Parachuting, HighAltitudeTraining, QuickDecisionMaking, AttentionToDetail, Multitasking",I want to join defence field
12th,Defence,Coast Gaurd,,"Adventure, Oceanography, EnvironmentalProtection, MechanicalRepair, NavigationTechnology, DisasterResponse, EmergencyPreparedness, Climbing, HighEnduranceTasks, RiskManagement, TacticalPlanning, StrategicThinking","Leadership, Endurance,  Surveillance, CoastalSecurity, VesselMaintenance, Stamina, Firefighting, CPR, DamageControl, CrisisManagement, DisasterResponse, EmergencyRescue,IncidentCommand, EvacuationPlanning, SituationalAwareness, StrategicThinking, RiskManagement",I want to join defence field
12th,Defence,Border Security,,"Protection, Safety, Defense, Service, Security, Duty, Law, Order, Surveillance, Patrolling, Monitoring, Detection, Interception, Investigation, Reconnaissance, Reporting, Navigation, Enforcement, Endurance, Outdoor, Vehicles, Marching, Weapons, Tracking, Observation, Resilience","Surveillance, Patrolling, Observation, Communication, Vigilance, Endurance, RadioOperation, FirstAid, VehicleOperation, ThermalImaging, DroneOperation, EquipmentMaintenance, SecuritySystems, Alertness, ProblemSolving, RiskAssessment, AttentionToDetail, QuickThinking,daptability, StressManagement, Memory, Focus, Strategy",I want to join defence field
12th,Government Services, IAS (Indian Administrative Service),,"Governance, Policy-making, Public Administration, Development","Leadership, Decision-making, Analytical Thinking, Communication, Problem-solving",I want to join civil services
12th,Government Services,IPS (Indian Police Service),,"Law Enforcement, Internal Security, Crime Prevention, Public Safety","Leadership, Physical Fitness, Investigation, Strategy, Crisis Management",I want to join civil services
12th,Government Services,IFS (Indian Foreign Service),,"Diplomacy, International Relations, Global Affairs, Representation","Communication, Negotiation, Foreign Languages, Cultural Awareness, Analytical Skills",I want to join civil services
12th,Government Services, IRS (Indian Revenue Service),," Taxation, Financial Administration, Policy Implementation"," Finance Knowledge, Analysis, Integrity, Investigation, Problem-solving",I want to join civil services
12th,Government Services,IFS (Indian Forest Service),,"Environment Conservation, Wildlife Protection, Forestry Management"," Ecology Knowledge, Fieldwork, Management, Problem-solving, Physical Stamina",I want to join civil services
12th,Hotel Management,Hotel Management with BHM,,"Travel, Food, Culture, Events, Hosting, Service, Cooking, Tourism, Luxury, Entertainment","Communication, Leadership, Multitasking, Organization, Teamwork, Presentation, Adaptability, Problem-solving, Timekeeping, Etiquette",I want to become a successful chef
12th,Photography,Photography with BFA/BA/B.SC,,"Photography, Art, Nature, Travel, Fashion, Portraits, Lighting, Editing, Storytelling, Creativity","Composition, Framing, Editing, Lighting, Direction, Focus, Visualization, Communication, Organization, Marketing",I want to become a successful photographer
12th,Choreography, Cheoreography with BPA,,"Dance, Music, Performance, Expression, Rhythm, Stage, Movement, Creativity, Art, Fitness","Choreography, Coordination, Timing, Leadership, Planning, Teaching, Innovation, Communication, Discipline, Visualization",I want to become a successful choreographer
12th,Sports ,Sports with B.P.Ed,,"Fitness, Competition, Teamwork, Training, Games, Athletics, Endurance, Discipline, Adventure, Strategy","Agility, Strength, Coordination, Leadership, Stamina, Focus, Reflexes, Teamwork, Discipline, Communication",I want to become a sport person
12th,Art Galleries ,Art Galleries with B.A,,"Art, Painting, Sculpture, History, Culture, Exhibits, Design, Creativity, Aesthetics, Expression","Curation, Observation, Communication, Organization, Cataloging, Presentation, Research, Networking, Creativity, Management",I want to become a successful artist
Graduation,Law,Lawyer(advocate) with LL.M Degree,"Advocate, Legal Advisor, Legal Consultant, Public Prosecutor, Corporate Lawyer, Criminal Lawyer, Civil Lawyer, Tax Lawyer, Family Lawyer, Intellectual Property Lawyer, Litigation Associate, Legal Officer, Legal Analyst, Legal Counsel, Solicitor, Notary","Justice, Legal Rights, Courtroom Advocacy, Legal Research","Argumentation, Communication, Critical Thinking, Research, Persuasion",I want to become a successful Lawyer.
Graduation,law ,Judge with LL.M Degree,"Judge, Magistrate, District Judge, Sessions Judge, Chief Justice, High Court Judge, Supreme Court Judge, Tribunal Judge, Judicial Officer, Legal Advisor, Court Registrar, Judicial Clerk, Law Secretary, Public Prosecutor, Legal Consultant","Law Interpretation, Justice Delivery, Legal Ethics, Decision-making","Legal Knowledge, Impartiality, Analytical Reasoning, Patience, Integrity","I want to become a Judge, lawyer."
Graduation,Law ,Corporate Lawyer with LL.M Degree,"Corporate Lawyer, Legal Advisor, Legal Counsel, Corporate Counsel, In-House Counsel, Compliance Officer, Legal Manager, Contract Manager, Mergers and Acquisitions Lawyer, Regulatory Counsel, Legal Associate, General Counsel, Risk Manager, Legal Consultant, Company Secretary","Business Law, Mergers & Acquisitions, Company Regulations","Commercial Awareness, Negotiation, Contract Drafting, Problem-solving, Communication","I want to become a successful lawyer, Coporpate Lawyer "
Graduation,Law ,Criminal Lawyer with LL.M Degree,"Criminal Lawyer, Defense Attorney, Public Prosecutor, Legal Advisor (Criminal Law), Criminal Defense Counsel, Assistant District Attorney, Legal Consultant (Criminal), Trial Lawyer, Litigation Attorney, Legal Associate (Criminal), Criminal Law Advocate, Prosecuting Attorney, Public Defender","Crime Cases, Criminal Justice, Defense and Prosecution","Investigation, Argumentation, Analytical Skills, Communication, Resilience",I want to become a Criminal Lawyer.
Graduation,Law ,Family Lawyer with LL.M Degree,"Family Lawyer, Divorce Attorney, Child Custody Lawyer, Legal Advisor (Family Law), Mediation Lawyer, Family Law Advocate, Legal Consultant (Family Matters), Adoption Lawyer, Domestic Violence Attorney, Guardianship Lawyer, Alimony Specialist, Family Court Attorney","Marriage Law, Divorce Cases, Child Custody, Family Disputes","Mediation, Counseling, Negotiation, Patience, Emotional Intelligence",I want to become a successful family lawyer.
Graduation,Engineering ,Computer Science and Engineering with ME/M-TECH,"Software Engineer, Full Stack Developer, Backend Developer, Frontend Developer, Data Scientist, Machine Learning Engineer, AI Engineer, DevOps Engineer, Systems Analyst, Cloud Engineer, Cybersecurity Analyst, Database Administrator, Network Engineer, Mobile App Developer, Web Developer, Embedded Systems Engineer, Game Developer, QA Engineer, IT Consultant, Research Scientist","Web Development, Software Development, Frontend Development, Full stack development, Artificial Intelligence, Machine Learning, Data science, Cyber Security, Data Analytics, cloud Computing.","C, C++, Java, Python, JavaScript, Data structures and algorithms, Database management system, operating systems, Cloud computing, Blockchain Development.","I want to become a successfull software developer, software engineer, web developer, Frontend developer, backend developer, full stack developer. "
Graduation,Engineering ,Mechanical Engineering with ME/M-TECH,"Mechanical Engineer, Design Engineer, Maintenance Engineer, Production Engineer, Quality Engineer, HVAC Engineer, Automotive Engineer, Aerospace Engineer, Thermal Engineer, Manufacturing Engineer, Project Engineer, R&D Engineer, Mechatronics Engineer, CAD Engineer, Robotics Engineer, Plant Engineer, Tooling Engineer, Marine Engineer","Interest in machines, Cars, Engines, Product Design, Automobiles, 3D printing and prototyping, Industrial automation and robotics, Product innovation and design.","Mathematics and Physics, AutoCAD, Engineering fundamentals, Thermodynamics, Fluid Mechanics, Material Science, Manufacturing Processes, Robotics, Problem Solving, HIVAC Systems, Finite Element Analysis, Energy Systems, Mechatronics.",I want to become a successful mechanical engineer.
Graduation,Engineering ,Civil Engineering with ME/M-TECH,"Civil Engineer, Site Engineer, Structural Engineer, Project Engineer, Construction Manager, Geotechnical Engineer, Transportation Engineer, Environmental Engineer, Surveyor, Design Engineer, Planning Engineer, Quantity Surveyor, Water Resources Engineer, Urban Planner, Highway Engineer, Building Inspector, Estimation Engineer","Passion for building structures, Urban development, environmental sustainability, Designing eco-friendly cities, skyscraper and mega-structure projects, Green building technology, Bridge architecture and design.","Structural Analysis, AutoCAD, Construction Management, Surveying, Estimation and costing, Geotechnical Engineering, Building Information Modelling, Urban Planning, Soil Mechanics, Transportation Engineering, Environmental Engineering. ",I want to become a successful civil engineer
Graduation,Engineering ,Electrical Engineering with ME/M-TECH,"Electrical Engineer, Power Systems Engineer, Control Systems Engineer, Design Engineer, Electronics Engineer, Instrumentation Engineer, Maintenance Engineer, Project Engineer, Circuit Design Engineer, Test Engineer, Embedded Systems Engineer, Automation Engineer, Energy Consultant, Hardware Engineer, Substation Engineer, Electrical Site Engineer","Power Systems, Electrical Machines, Electric innovation, Power generation, Energy conservation, Smart grids, Electronics, Electric vehicles and motors, Power transmission.","Power systems, Electrical Machines, Control systems, Circuit Theory, MATLAB/Simulink, Renewable, Energy, Electronics, Smart Grids Technology, SCADA Systems, High voltage Engineering, Energy Storage Systems.",I want to become a successful Electrical engineer
Graduation,Engineering ,Electronics and Telecommunication Engineering with ME/M-TECH,"Electronics Engineer, Telecommunication Engineer, Network Engineer, RF Engineer, Embedded Systems Engineer, Signal Processing Engineer, VLSI Engineer, IoT Engineer, Hardware Design Engineer, Systems Engineer, Satellite Communication Engineer, Wireless Communication Engineer, Optical Fiber Engineer, Test Engineer, PCB Design Engineer, Telecom Analyst","Fascination with gadgets, Electronics, Wireless systems, Building Circuits, Internet of Things, Mobile Communication, Embedded Systems, Smart devices and home automation, radio technology, Satellite communication, Tech gadgets teardown, Electronics DIY projects.","Circuit Design, Embedded Systems, VLSI Design, Communication Systems, Signal, Processing, Programming(Verilog, C), PCB Designing, Internet of Things, FPGA Programming, Wireless Communication Protocols, Artificial Neural Networks.",I want to become a successful Electronics and Telecommunication Engineer
Graduation,Engineering,Mining Engineering with ME/M-TECH,"Mining Engineer, Mine Planner, Mine Surveyor, Drilling Engineer, Blasting Engineer, Ventilation Engineer, Safety Officer, Mineral Processing Engineer, Geotechnical Engineer, Quarry Manager, Exploration Geologist, Mine Manager, Underground Mining Engineer, Surface Mining Engineer, Environmental Engineer (Mining), Mining Consultant","Interest in Natural resources, Mining technology, Earth science, Environmental impact of mining, Exploring remote areas for resources, Sustainable mining practices, Metallurgy and mineral processing, Geological field work.","Rock Mechanics, Mine Surveying, Mineral Processing, Safety Management, Environmental Engineering, Geology, Mine planning and Design, Drilling and Blasting Techniques, Mineral Economics, Underground and Surface mining techniques, Mine Health and Safety.",I want to become a successful mining engineer
Graduation,Medical,MBBS ,"Doctor, General Practitioner, Surgeon, Pediatrician, Cardiologist, Dermatologist, Neurologist, Psychiatrist, Orthopedic Surgeon, Obstetrician, Gynecologist, Anesthesiologist, Ophthalmologist, ENT Specialist, Radiologist, Pathologist, Emergency Medicine Specialist, Family Physician, Medical Consultant","Healthcare, Problem-solving, Surgery, Diagnosis, Medicine","Anatomy, Communication, Critical thinking, Decision-making, Stress Management",I want to become a successful doctor.
Graduation,Medical,Dentist with  BDS,"Dentist, Orthodontist, Periodontist, Endodontist, Oral Surgeon, Pediatric Dentist, Prosthodontist, Dental Hygienist, Dental Assistant, Dental Technician, Cosmetic Dentist, Implantologist, Maxillofacial Surgeon, Forensic Dentist, Public Health Dentist","Oral, Hygiene, Procedures, Dentistry, Technology","Manual dexterity, Communication, Diagnosis, Anatomy, Patient care",I want to become a successful doctor.
Graduation,Medical,BHMS,"Homeopathic Physician, Clinical Homeopath, Pediatric Homeopath, Dermatology Homeopath, Obstetrics Homeopath, Homeopathic Consultant, Researcher (Homeopathy), Educator (Homeopathy), Hospital Homeopath, Public Health Homeopath, Homeopathic Pharmacist, Wellness Coach, Integrative Medicine Specialist, Homeopathic Practitioner, Telemedicine Homeopath","Alternative medicine, Holistic health, Natural remedies, Patient care","Diagnosis, Homeopathy, Research, Empathy, Analytical skills",I want to become a successful doctor
Graduation,Medical,Pharmacy with M-phram,"Homeopathic Physician, Clinical Homeopath, Pediatric Homeopath, Dermatology Homeopath, Obstetrics Homeopath, Homeopathic Consultant, Researcher (Homeopathy), Educator (Homeopathy), Hospital Homeopath, Public Health Homeopath, Homeopathic Pharmacist, Wellness Coach, Integrative Medicine Specialist, Homeopathic Practitioner, Telemedicine Homeopath","Pharmaceuticals, Drug formulation, Medication, Patient health","Pharmacology, chemistry, Accuracy, Organization, Counseling",I want to become a successful doctor
Graduation,Medical,Gynaecologist with MBBS,"Gynecologist, Obstetrician-Gynecologist, Reproductive Endocrinologist, Maternal-Fetal Medicine Specialist, Gynecologic Oncologist, Urogynecologist, Minimally Invasive Gynecologic Surgeon, Infertility Specialist, Perinatologist, Women’s Health Specialist, Academic Gynecologist, Clinical Researcher (Ob/Gyn), Nurse Practitioner (Ob/Gyn), Physician Assistant (Ob/Gyn)","Reproductive health, Pregnancy, Childbirth, Women's health","Obstetrics, Surgery, Communication, Diagnosis, Patient care",I want to become a successful doctor
Graduation,Defence,Army,"Soldier, Infantry Officer, Artillery Officer, Armored Corps Officer, Combat Engineer, Signals Officer, Intelligence Officer, Logistics Officer, Medical Officer, Legal Officer, Chaplain, Pilot (Army Aviation), Special Forces Operator, Cyber Warfare Officer, UAV Operator, Public Affairs Officer, Training Officer, Military Police, Reconnaissance Officer, Procurement Officer, Strategic Planner","Leadership, Strategy, Survival, Weapons, Strategy Games Command, Training, StrengthBuilding, CombatFitness, StrategyDevelopment, NationalUnity, Patriotism"," Discipline,Leadership, Teamwork, Strategy, Endurance Strength, Focus ,Courage, Self Defense, Weapons Handling, SurvivalTraining,FirstAid, military planning ",I want to join defence field
Graduation,Defence,Navy,"Naval Officer, Submarine Officer, Surface Warfare Officer, Naval Aviator, Marine Corps Officer, Naval Intelligence Officer, Naval Architect, Oceanographer, Naval Engineer, Logistics Officer, Medical Officer (Navy), Dental Officer (Navy), Supply Officer, Legal Officer (JAG), Chaplain, Communications Officer, Cyber Warfare Officer, Explosive Ordnance Disposal Officer, Diver, Public Affairs Officer","Navigation, SubmarineWarfare, SeaManship, Radar, Sonar, Swimming, CombatFitness, Oceanography, NavalTechnology, InternationalWater","Under water Survival, Weapon Systems, Radar Systems, Sonar Technology, Ship Maintenance, Crisis Management, Resource Management, Combat Swimming, Planning, Multi-Tasking, Navigation, Damage Control, Emergency Response, Search And Rescue",I want to join defence field
Graduation,Defence,Air force,"Pilot, Combat Controller, Air Traffic Controller, Flight Engineer, Aeronautical Engineer, Intelligence Officer, Cyber Warfare Officer, Logistics Officer, Medical Officer (Air Force), Dental Officer (Air Force), Legal Officer (JAG), Chaplain, Pararescueman, Special Tactics Officer, Aircraft Maintenance Officer, Aerospace Physiologist, Weather Officer, Public Affairs Officer, Safety Officer, Instructor Pilot","AirWarfare, FighterJet, Bombing, AirDefense, Dogfighting, AirPatrolling, Propulsion, Avionics, AirCraftDesign, FlightControl, Navigation, Command, TacticalLeadership","Focus, Piloting, FlightControl, AirRefueling, CombatFlying, AircraftMaintenance, AirDefense, SearchAndRescue, SurvivalSkills, WeaponsHandling, Fitness, Stamina, Parachuting, HighAltitudeTraining, QuickDecisionMaking, AttentionToDetail, Multitasking",I want to join defence field
Graduation,Defence,Coast Gaurd,"Coast Guard Officer, Deck Officer, Navigation Officer, Engineering Officer, Medical Officer, Legal Officer (JAG), Intelligence Officer, Logistics Officer, Communications Officer, Maritime Law Enforcement Officer, Search & Rescue Coordinator, Aviation Pilot, Diver, Environmental Protection Officer, Port Security Specialist, Training Officer, Public Affairs Officer, Cybersecurity Officer, Helicopter Pilot, Operations Manager","Adventure, Oceanography, EnvironmentalProtection, MechanicalRepair, NavigationTechnology, DisasterResponse, EmergencyPreparedness, Climbing, HighEnduranceTasks, RiskManagement, TacticalPlanning, StrategicThinking","Leadership, Endurance,  Surveillance, CoastalSecurity, VesselMaintenance, Stamina, Firefighting, CPR, DamageControl, CrisisManagement, DisasterResponse, EmergencyRescue,IncidentCommand, EvacuationPlanning, SituationalAwareness, StrategicThinking, RiskManagement",I want to join defence field
Graduation,Defence,Border Security,"Border Patrol Agent, Immigration Officer, Customs Officer, Border Security Officer, Surveillance Operator, K9 Handler, Checkpoint Supervisor, Border Intelligence Analyst, Maritime Border Patrol Officer, Air Border Security Officer, Tactical Response Unit Member, Anti-Smuggling Officer, Cyber Border Security Analyst, Field Operations Agent, Strategic Operations Planner, Training Coordinator, Public Affairs Officer, Drone Operator, Search & Rescue Officer, Rapid Response Officer","Protection, Safety, Defense, Service, Security, Duty, Law, Order, Surveillance, Patrolling, Monitoring, Detection, Interception, Investigation, Reconnaissance, Reporting, Navigation, Enforcement, Endurance, Outdoor, Vehicles, Marching, Weapons, Tracking, Observation, Resilience","Surveillance, Patrolling, Observation, Communication, Vigilance, Endurance, RadioOperation, FirstAid, VehicleOperation, ThermalImaging, DroneOperation, EquipmentMaintenance, SecuritySystems, Alertness, ProblemSolving, RiskAssessment, AttentionToDetail, QuickThinking,daptability, StressManagement, Memory, Focus, Strategy",I want to join defence field
Graduation,Government Services, IAS (Indian Administrative Service),"District Collector, Sub‑Divisional Magistrate, Deputy Secretary, Under Secretary, Joint Secretary, Additional Secretary, Secretary, Chief Secretary, Development Commissioner, Revenue Commissioner, Municipal Commissioner, Election Commissioner, Director General, Principle Secretary, Home Secretary, Finance Secretary, Health Secretary, Education Secretary, Public Works Secretary, Transport Commissioner","Governance, Policy-making, Public Administration, Development","Leadership, Decision-making, Analytical Thinking, Communication, Problem-solving",I want to join civil services
Graduation,Government Services,IPS (Indian Police Service),"Assistant Superintendent of Police (ASP), Sub‑Divisional Police Officer (SDPO), Superintendent of Police (SP), Senior Superintendent of Police (SSP), Deputy Inspector General of Police (DIG), Inspector General of Police (IG), Additional Director General of Police (ADG), Director General of Police (DGP), Commissioner of Police, Deputy Commissioner of Police (DCP), Joint Commissioner of Police (Jt CP), Assistant Commissioner of Police (ACP), Station House Officer (SHO), Cyber Crime Coordinator, Intelligence Officer, Training Director, Traffic Commissioner, Special Task Force Commander, Armed Police Battalion Commander, Vigilance Commissioner","Law Enforcement, Internal Security, Crime Prevention, Public Safety","Leadership, Physical Fitness, Investigation, Strategy, Crisis Management",I want to join civil services
Graduation,Government Services,IFS (Indian Foreign Service),"Third Secretary, Second Secretary, First Secretary, Counsellor, Minister (Deputy Head of Mission), Deputy Chief of Mission, Consul General, Consular Officer, Political Officer, Economic Officer, Trade Commissioner, Cultural Affairs Officer, Protocol Officer, Ambassador, High Commissioner, Permanent Representative (UN), Deputy Permanent Representative, Defence Attaché, Press Attaché, Charge d’Affaires","Diplomacy, International Relations, Global Affairs, Representation","Communication, Negotiation, Foreign Languages, Cultural Awareness, Analytical Skills",I want to join civil services
Graduation,Government Services, IRS (Indian Revenue Service),"Tax Assistant, Inspector of Income Tax, Income Tax Officer, Assistant Commissioner of Income Tax, Deputy Commissioner of Income Tax, Joint Commissioner of Income Tax, Commissioner of Income Tax, Additional Commissioner of Income Tax, Principal Commissioner of Income Tax, Chief Commissioner of Income Tax, Director General of Income Tax (Investigation), Enforcement Officer, Prosecution Officer, Audit Officer, Administrative Officer"," Taxation, Financial Administration, Policy Implementation"," Finance Knowledge, Analysis, Integrity, Investigation, Problem-solving",I want to join civil services
Graduation,Government Services,IFS (Indian Forest Service),"Third Secretary, Second Secretary, First Secretary, Counsellor, Minister, Deputy Chief of Mission, Consul General, Political Officer, Economic Officer, Trade Commissioner, Cultural Affairs Officer, Protocol Officer, Ambassador, High Commissioner, Permanent Representative, Defence Attaché, Press Attaché, Charge d’Affaires","Environment Conservation, Wildlife Protection, Forestry Management"," Ecology Knowledge, Fieldwork, Management, Problem-solving, Physical Stamina",I want to join civil services
Graduation,Hotel Management,Hotel Management with MHM,"Hotel Manager, General Manager, Front Office Manager, Guest Relations Manager, Housekeeping Manager, Food & Beverage Manager, Restaurant Manager, Executive Chef, Banquet Manager, Events Manager, Sales Manager, Revenue Manager, Catering Manager, Concierge, Spa Manager, Maintenance Manager, Human Resources Manager, Training Manager, Operations Manager","Travel, Food, Culture, Events, Hosting, Service, Cooking, Tourism, Luxury, Entertainment","Communication, Leadership, Multitasking, Organization, Teamwork, Presentation, Adaptability, Problem-solving, Timekeeping, Etiquette",I want to become a successful chef
Graduation,Photography,Photography with MFA/MA/M.SC,"Photographer, Photojournalist, Portrait Photographer, Wedding Photographer, Fashion Photographer, Commercial Photographer, Product Photographer, Event Photographer, Wildlife Photographer, Sports Photographer, Studio Photographer, Freelance Photographer, Photo Editor, Photography Assistant, Drone Photographer, Travel Photographer, Fine Art Photographer, Stock Photographer, Cinematographer, Photo Retoucher","Photography, Art, Nature, Travel, Fashion, Portraits, Lighting, Editing, Storytelling, Creativity","Composition, Framing, Editing, Lighting, Direction, Focus, Visualization, Communication, Organization, Marketing",I want to become a successful photographer
Graduation,Choreography, Cheoreography with MPA,"Choreographer, Dance Instructor, Dance Captain, Rehearsal Director, Movement Coach, Dance Coach, Artistic Director, Creative Director, Performance Director, Stage Choreographer, Musical Theatre Choreographer, Commercial Choreographer, Dance Consultant, Freelance Choreographer, Ballet Master/Mistress, Wardrobe Coordinator, Dance Therapist, Choreography Assistant, Dance Notator, Production Choreographer","Dance, Music, Performance, Expression, Rhythm, Stage, Movement, Creativity, Art, Fitness","Choreography, Coordination, Timing, Leadership, Planning, Teaching, Innovation, Communication, Discipline, Visualization",I want to become a successful choreographer
Graduation,Sports ,Sports with M.P.Ed,"Athlete, Coach, Sports Manager, Athletic Trainer, Sports Analyst, Sports Agent, Referee, Umpire, Sports Journalist, Sports Commentator, Strength & Conditioning Coach, Physical Therapist, Sports Marketing Manager, Event Coordinator, Sports Scout, Team Physician, Sports Psychologist, Facility Manager, Operations Director, Performance Analyst","Fitness, Competition, Teamwork, Training, Games, Athletics, Endurance, Discipline, Adventure, Strategy","Agility, Strength, Coordination, Leadership, Stamina, Focus, Reflexes, Teamwork, Discipline, Communication",I want to become a sport person
Graduation,Art Galleries ,Art Galleries with M.A,"Gallery Manager, Curator, Exhibition Coordinator, Registrar, Collection Manager, Art Handler, Gallery Director, Development Officer, Visitor Services Manager, Marketing Manager, Education Officer, Conservator, Archivist, Docent, Sales Associate, Framer, Installation Specialist, Public Relations Officer, Art Consultant, Outreach Coordinator","Art, Painting, Sculpture, History, Culture, Exhibits, Design, Creativity, Aesthetics, Expression","Curation, Observation, Communication, Organization, Cataloging, Presentation, Research, Networking, Creativity, Management",I want to become a successful artist
"""

stop_words = set(stopwords.words('english'))
punctuations = set(string.punctuation)

def preprocess_text(text):
    if not text or text.lower() == "nan":
        return set()
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words and t not in punctuations and len(t) > 1]
    return set(tokens)

def parse_csv_data(csv_text):
    lines = csv_text.strip().splitlines()
    reader = csv.DictReader(lines)
    data_list = []
    for row in reader:
        # Strip keys to avoid spaces causing issues
        row = {k.strip(): v.strip() if isinstance(v, str) else v for k, v in row.items()}
        row['qualifications_tokens'] = preprocess_text(row.get('Qualifications', ''))
        row['Skills_tokens'] = preprocess_text(row.get('Skills', ''))
        row['Interests_tokens'] = preprocess_text(row.get('Interests', ''))
        row['Goals_tokens'] = preprocess_text(row.get('Goals', ''))
        data_list.append(row)
    return data_list

def jaccard_similarity(set1, set2):
    if not set1 and not set2:
        return 1.0
    intersection = set1.intersection(set2)
    union = set1.union(set2)
    return float(len(intersection)) / len(union)

data = parse_csv_data(csv_data)

def suggest_job(user_qualifications, user_skills, user_interests, user_goals, data):
    user_qualifications_tokens = preprocess_text(user_qualifications)
    user_skills_tokens = preprocess_text(user_skills)
    user_interests_tokens = preprocess_text(user_interests)
    user_goals_tokens = preprocess_text(user_goals)

    best_score = -1.0
    best_row = None

    for row in data:
        sim_qualifications = jaccard_similarity(user_qualifications_tokens, row['qualifications_tokens'])
        sim_skills = jaccard_similarity(user_skills_tokens, row['Skills_tokens'])
        sim_interests = jaccard_similarity(user_interests_tokens, row['Interests_tokens'])
        sim_goals = jaccard_similarity(user_goals_tokens, row['Goals_tokens'])
        avg_sim = (sim_qualifications + sim_skills + sim_interests + sim_goals) / 4

        if avg_sim > best_score:
            best_score = avg_sim
            best_row = row

    if best_row:
        return post_process_results(best_row['Fields'], best_row['Job Titles'], user_qualifications)
    else:
        return None, None

def post_process_results(field, job_title, user_qualifications):
    if user_qualifications.lower() == "12th":
        return field, None
    elif user_qualifications.lower() == "graduation":
        return field, job_title
    return None, None

def suggest(user_qualifications, skills, interests, goals):
    return suggest_job(user_qualifications, skills, interests, goals, data)

def main():
    print("Enter your qualifications (e.g. 12th or Graduation):")
    user_qualifications = input().strip()
    print("Enter your skills (comma separated):")
    user_skills = input().strip()
    print("Enter your interests (comma separated):")
    user_interests = input().strip()
    print("Enter your goals (sentence or keywords):")
    user_goals = input().strip()

    field, job_title = suggest_job(user_qualifications, user_skills, user_interests, user_goals, data)
    print("\nSuggested field:", field)
    print("\nSuggested Job Title(s):", job_title)

if __name__ == "__main__":
    main()
